# Generated by Django 5.1.6 on 2025-02-08 08:11

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=16)),
                ('model', models.CharField(max_length=16)),
                ('year', models.DateField(auto_now=True)),
                ('fuel_type', models.DecimalField(decimal_places=1, max_digits=2)),
                ('transmission', models.CharField(max_length=16)),
                ('image', models.ImageField(upload_to='cars_images/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('role_status', models.CharField(choices=[('Администратор', 'Администратор'), ('Продавец', 'Продавец'), ('Покупатель', 'Покупатель')], default='Администратор', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_price', models.PositiveSmallIntegerField(default=0)),
                ('min_price', models.PositiveSmallIntegerField(default=0)),
                ('start_time', models.DateField(auto_now=True)),
                ('end_time', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('Активен', 'Активен'), ('Завершен', 'Завершен'), ('Отменен', 'Отменен')], default='Активен', max_length=10)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars_store.car')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars_store.auction')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars_store.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars_store.userprofile'),
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars_store.auction')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars_store.userprofile')),
            ],
        ),
    ]
